name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -d ./...

      - name: Test custom
        run: env $BOT_TOKEN $BOT_CHANNEL_ID go run main.go custom --customMsg="my custom message"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_CHANNEL_ID: ${{ secrets.BOT_CHANNEL_ID_TEST }}

      - name: Test forecast
        run: env $BOT_TOKEN $BOT_CHANNEL_ID go run main.go forecast --xmlId=${{ secrets.XML_ID }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_CHANNEL_ID: ${{ secrets.BOT_CHANNEL_ID_TEST }}

      - name: Test waves map
        run: env $BOT_TOKEN $BOT_CHANNEL_ID go run main.go forecastMap --zoneId=${{ secrets.ZONE_ID }} --wind="false"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_CHANNEL_ID: ${{ secrets.BOT_CHANNEL_ID_TEST }}

      - name: Test wind map
        run: env $BOT_TOKEN $BOT_CHANNEL_ID go run main.go forecastMap --zoneId=${{ secrets.ZONE_ID }} --wind="true"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_CHANNEL_ID: ${{ secrets.BOT_CHANNEL_ID_TEST }}
